### ISSUE TITLE
LESS css not included in pages

### ISSUE THREAD

**Issue by jamesprices** [IronCountySchoolDistrict/iep-printing#2]
The latest version of the plugin includes a .less file instead of a .css however in index.html and blank.html the old .css stylesheet is still referenced and Less.js is not loaded.

**Comment by jonesnc** [comment]
The code you see in the repo is not we deploy. We build our less into css using gulp, which spits out a styles.css file that is what you're seeing.

Is there a reason you're using the code in the repo instead of using what's in the v1.1.0 release?
